import os

from dotenv import load_dotenv

load_dotenv()

SNOWFLAKE_ACCOUNT = os.getenv("SNOWFLAKE_ACCOUNT")
SNOWFLAKE_USER = os.getenv("SNOWFLAKE_USER", "ADMIN")
SNOWFLAKE_PASSWORD = os.getenv("SNOWFLAKE_PASSWORD")
SNOWFLAKE_ROLE = os.getenv("SNOWFLAKE_ROLE", "IPL_ENGINEER_ROLE")
SNOWFLAKE_WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE", "IPL_INGEST_WH")
SNOWFLAKE_DATABASE = os.getenv("SNOWFLAKE_DATABASE", "IPL_ANALYTICS_DB")
SNOWFLAKE_SCHEMA = os.getenv("SNOWFLAKE_SCHEMA", "RAW")

STAGE_NAME = f"{SNOWFLAKE_DATABASE}.{SNOWFLAKE_SCHEMA}.IPL_STAGE"
FILE_FORMAT = f"{SNOWFLAKE_DATABASE}.{SNOWFLAKE_SCHEMA}.IPL_JSON_FORMAT"
RAW_TABLE = f"{SNOWFLAKE_DATABASE}.{SNOWFLAKE_SCHEMA}.RAW_MATCH_JSON"
